#ddev-generated
services:
  redis:
    container_name: ddev-${DDEV_SITENAME}-redis
    image: redis:8.10.1@sha256:298e5b3bc566bade82f46ad5511777a4a07a294097ce16ada2f6a42be5239df5
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - "./redis:/usr/local/etc/redis"
      - "redis:/data"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

volumes:
  redis:
